# Generated by Django 6.0.5 on 2026-06-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_event_slug_alter_event_organizer_and_more'),
        ('payments', '0002_alter_payout_organizer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ogarnizer',
        ),
    ]
