# Generated by Django 6.0.5 on 2026-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_order_tickets_ord_status_44f72e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
