# Generated by Django 6.0.5 on 2026-06-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
        ('payments', '0001_initial'),
        ('tickets', '0002_order_tickets_ord_status_44f72e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider_reference'], name='payments_tr_provide_9bbfff_idx'),
        ),
    ]
